# Calculation Variants
VARIANT_WORDS = 'words'
VARIANT_WORD_LENGTHS = 'wordLengths'

# Grading Variants
GRADING_VARIANT_HARMONIC = 'harmonic'
GRADING_VARIANT_WEIGHTED = 'weighted'

# Paths
LABELS_PATH = r'..\assets\labels'
TMP_PATH = r'..\tmp'

# Evaluation
MOODLE_POINTS = 'MOODLE_POINTS'
CLASSIFICATION = 'CLASSIFICATION'
WEIGHT = 'WEIGHT'
POINTS_HARMONIC = 'POINTS_HARMONIC'
POINTS_WEIGHTED = 'POINTS_WEIGHTED'
HARMONIC_MEAN = 'HARMONIC_MEAN'
